// Package unsent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package unsent

import (
	"encoding/json"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateApiKeyJSONBodyPermission.
const (
	FULL    CreateApiKeyJSONBodyPermission = "FULL"
	SENDING CreateApiKeyJSONBodyPermission = "SENDING"
)

// Defines values for GetSuppressionsParamsReason.
const (
	GetSuppressionsParamsReasonCOMPLAINT   GetSuppressionsParamsReason = "COMPLAINT"
	GetSuppressionsParamsReasonHARDBOUNCE  GetSuppressionsParamsReason = "HARD_BOUNCE"
	GetSuppressionsParamsReasonMANUAL      GetSuppressionsParamsReason = "MANUAL"
	GetSuppressionsParamsReasonUNSUBSCRIBE GetSuppressionsParamsReason = "UNSUBSCRIBE"
)

// Defines values for AddSuppressionJSONBodyReason.
const (
	AddSuppressionJSONBodyReasonCOMPLAINT   AddSuppressionJSONBodyReason = "COMPLAINT"
	AddSuppressionJSONBodyReasonHARDBOUNCE  AddSuppressionJSONBodyReason = "HARD_BOUNCE"
	AddSuppressionJSONBodyReasonMANUAL      AddSuppressionJSONBodyReason = "MANUAL"
	AddSuppressionJSONBodyReasonUNSUBSCRIBE AddSuppressionJSONBodyReason = "UNSUBSCRIBE"
)

// GetReputationParams defines parameters for GetReputation.
type GetReputationParams struct {
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`
}

// GetTimeSeriesParams defines parameters for GetTimeSeries.
type GetTimeSeriesParams struct {
	Days   *string `form:"days,omitempty" json:"days,omitempty"`
	Domain *string `form:"domain,omitempty" json:"domain,omitempty"`
}

// CreateApiKeyJSONBody defines parameters for CreateApiKey.
type CreateApiKeyJSONBody struct {
	Name       string                          `json:"name"`
	Permission *CreateApiKeyJSONBodyPermission `json:"permission,omitempty"`
}

// CreateApiKeyJSONBodyPermission defines parameters for CreateApiKey.
type CreateApiKeyJSONBodyPermission string

// CreateCampaignJSONBody defines parameters for CreateCampaign.
type CreateCampaignJSONBody struct {
	BatchSize     *int                            `json:"batchSize,omitempty"`
	Bcc           *CreateCampaignJSONBody_Bcc     `json:"bcc,omitempty"`
	Cc            *CreateCampaignJSONBody_Cc      `json:"cc,omitempty"`
	ContactBookId string                          `json:"contactBookId"`
	Content       *string                         `json:"content,omitempty"`
	From          string                          `json:"from"`
	Html          *string                         `json:"html,omitempty"`
	Name          string                          `json:"name"`
	PreviewText   *string                         `json:"previewText,omitempty"`
	ReplyTo       *CreateCampaignJSONBody_ReplyTo `json:"replyTo,omitempty"`

	// ScheduledAt Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
	ScheduledAt *string `json:"scheduledAt,omitempty"`
	SendNow     *bool   `json:"sendNow,omitempty"`
	Subject     string  `json:"subject"`
}

// CreateCampaignJSONBodyBcc0 defines parameters for CreateCampaign.
type CreateCampaignJSONBodyBcc0 = string

// CreateCampaignJSONBodyBcc1 defines parameters for CreateCampaign.
type CreateCampaignJSONBodyBcc1 = []string

// CreateCampaignJSONBody_Bcc defines parameters for CreateCampaign.
type CreateCampaignJSONBody_Bcc struct {
	union json.RawMessage
}

// CreateCampaignJSONBodyCc0 defines parameters for CreateCampaign.
type CreateCampaignJSONBodyCc0 = string

// CreateCampaignJSONBodyCc1 defines parameters for CreateCampaign.
type CreateCampaignJSONBodyCc1 = []string

// CreateCampaignJSONBody_Cc defines parameters for CreateCampaign.
type CreateCampaignJSONBody_Cc struct {
	union json.RawMessage
}

// CreateCampaignJSONBodyReplyTo0 defines parameters for CreateCampaign.
type CreateCampaignJSONBodyReplyTo0 = string

// CreateCampaignJSONBodyReplyTo1 defines parameters for CreateCampaign.
type CreateCampaignJSONBodyReplyTo1 = []string

// CreateCampaignJSONBody_ReplyTo defines parameters for CreateCampaign.
type CreateCampaignJSONBody_ReplyTo struct {
	union json.RawMessage
}

// ScheduleCampaignJSONBody defines parameters for ScheduleCampaign.
type ScheduleCampaignJSONBody struct {
	BatchSize *int `json:"batchSize,omitempty"`

	// ScheduledAt Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
	ScheduledAt *string `json:"scheduledAt,omitempty"`
}

// CreateContactBookJSONBody defines parameters for CreateContactBook.
type CreateContactBookJSONBody struct {
	Emoji      *string            `json:"emoji,omitempty"`
	Name       string             `json:"name"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// GetContactsParams defines parameters for GetContacts.
type GetContactsParams struct {
	Emails *string  `form:"emails,omitempty" json:"emails,omitempty"`
	Page   *float32 `form:"page,omitempty" json:"page,omitempty"`
	Limit  *float32 `form:"limit,omitempty" json:"limit,omitempty"`
	Ids    *string  `form:"ids,omitempty" json:"ids,omitempty"`
}

// CreateContactJSONBody defines parameters for CreateContact.
type CreateContactJSONBody struct {
	Email      string             `json:"email"`
	FirstName  *string            `json:"firstName,omitempty"`
	LastName   *string            `json:"lastName,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Subscribed *bool              `json:"subscribed,omitempty"`
}

// UpdateContactJSONBody defines parameters for UpdateContact.
type UpdateContactJSONBody struct {
	FirstName  *string            `json:"firstName,omitempty"`
	LastName   *string            `json:"lastName,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Subscribed *bool              `json:"subscribed,omitempty"`
}

// UpsertContactJSONBody defines parameters for UpsertContact.
type UpsertContactJSONBody = map[string]interface{}

// UpdateContactBookJSONBody defines parameters for UpdateContactBook.
type UpdateContactBookJSONBody struct {
	Emoji      *string            `json:"emoji,omitempty"`
	Name       *string            `json:"name,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// CreateDomainJSONBody defines parameters for CreateDomain.
type CreateDomainJSONBody struct {
	Name   string `json:"name"`
	Region string `json:"region"`
}

// ListEmailsParams defines parameters for ListEmails.
type ListEmailsParams struct {
	Page      *string    `form:"page,omitempty" json:"page,omitempty"`
	Limit     *string    `form:"limit,omitempty" json:"limit,omitempty"`
	StartDate *time.Time `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time `form:"endDate,omitempty" json:"endDate,omitempty"`
	DomainId  *struct {
		union json.RawMessage
	} `form:"domainId,omitempty" json:"domainId,omitempty"`
}

// ListEmailsParamsDomainId0 defines parameters for ListEmails.
type ListEmailsParamsDomainId0 = string

// ListEmailsParamsDomainId1 defines parameters for ListEmails.
type ListEmailsParamsDomainId1 = []string

// SendEmailJSONBody defines parameters for SendEmail.
type SendEmailJSONBody struct {
	Attachments *[]map[string]interface{} `json:"attachments,omitempty"`
	Bcc         *SendEmailJSONBody_Bcc    `json:"bcc,omitempty"`
	Cc          *SendEmailJSONBody_Cc     `json:"cc,omitempty"`
	From        string                    `json:"from"`

	// Headers Custom headers to included with the emails
	Headers     *map[string]string         `json:"headers,omitempty"`
	Html        *string                    `json:"html"`
	InReplyToId *string                    `json:"inReplyToId"`
	ReplyTo     *SendEmailJSONBody_ReplyTo `json:"replyTo,omitempty"`
	ScheduledAt *time.Time                 `json:"scheduledAt,omitempty"`

	// Subject Optional when templateId is provided
	Subject *string `json:"subject,omitempty"`

	// TemplateId ID of a template from the dashboard
	TemplateId *string              `json:"templateId,omitempty"`
	Text       *string              `json:"text"`
	To         SendEmailJSONBody_To `json:"to"`
	Variables  *map[string]string   `json:"variables,omitempty"`
}

// SendEmailParams defines parameters for SendEmail.
type SendEmailParams struct {
	// IdempotencyKey Pass the optional Idempotency-Key header to make the request safe to retry. The key can be up to 256 characters. The server stores the canonical request body and behaves as follows:
	//
	// - Same key + same request body → returns the original emailId with 200 OK without re-sending.
	// - Same key + different request body → returns 409 Conflict with code: NOT_UNIQUE so you can detect the mismatch.
	// - Same key while another request is still being processed → returns 409 Conflict; retry after a short delay or once the first request completes.
	//
	// Entries expire after 24 hours. Use a unique key per logical send (for example, an order or signup ID).
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// SendEmailJSONBodyBcc0 defines parameters for SendEmail.
type SendEmailJSONBodyBcc0 = string

// SendEmailJSONBodyBcc1 defines parameters for SendEmail.
type SendEmailJSONBodyBcc1 = []string

// SendEmailJSONBody_Bcc defines parameters for SendEmail.
type SendEmailJSONBody_Bcc struct {
	union json.RawMessage
}

// SendEmailJSONBodyCc0 defines parameters for SendEmail.
type SendEmailJSONBodyCc0 = string

// SendEmailJSONBodyCc1 defines parameters for SendEmail.
type SendEmailJSONBodyCc1 = []string

// SendEmailJSONBody_Cc defines parameters for SendEmail.
type SendEmailJSONBody_Cc struct {
	union json.RawMessage
}

// SendEmailJSONBodyReplyTo0 defines parameters for SendEmail.
type SendEmailJSONBodyReplyTo0 = string

// SendEmailJSONBodyReplyTo1 defines parameters for SendEmail.
type SendEmailJSONBodyReplyTo1 = []string

// SendEmailJSONBody_ReplyTo defines parameters for SendEmail.
type SendEmailJSONBody_ReplyTo struct {
	union json.RawMessage
}

// SendEmailJSONBodyTo0 defines parameters for SendEmail.
type SendEmailJSONBodyTo0 = string

// SendEmailJSONBodyTo1 defines parameters for SendEmail.
type SendEmailJSONBodyTo1 = []string

// SendEmailJSONBody_To defines parameters for SendEmail.
type SendEmailJSONBody_To struct {
	union json.RawMessage
}

// SendBatchEmailsJSONBody defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBody = []struct {
	Attachments *[]map[string]interface{}    `json:"attachments,omitempty"`
	Bcc         *SendBatchEmailsJSONBody_Bcc `json:"bcc,omitempty"`
	Cc          *SendBatchEmailsJSONBody_Cc  `json:"cc,omitempty"`
	From        string                       `json:"from"`

	// Headers Custom headers to included with the emails
	Headers     *map[string]string               `json:"headers,omitempty"`
	Html        *string                          `json:"html"`
	InReplyToId *string                          `json:"inReplyToId"`
	ReplyTo     *SendBatchEmailsJSONBody_ReplyTo `json:"replyTo,omitempty"`
	ScheduledAt *time.Time                       `json:"scheduledAt,omitempty"`

	// Subject Optional when templateId is provided
	Subject *string `json:"subject,omitempty"`

	// TemplateId ID of a template from the dashboard
	TemplateId *string                    `json:"templateId,omitempty"`
	Text       *string                    `json:"text"`
	To         SendBatchEmailsJSONBody_To `json:"to"`
	Variables  *map[string]string         `json:"variables,omitempty"`
}

// SendBatchEmailsParams defines parameters for SendBatchEmails.
type SendBatchEmailsParams struct {
	// IdempotencyKey Pass the optional Idempotency-Key header to make the request safe to retry. The key can be up to 256 characters. The server stores the canonical request body and behaves as follows:
	//
	// - Same key + same request body → returns the original emailId with 200 OK without re-sending.
	// - Same key + different request body → returns 409 Conflict with code: NOT_UNIQUE so you can detect the mismatch.
	// - Same key while another request is still being processed → returns 409 Conflict; retry after a short delay or once the first request completes.
	//
	// Entries expire after 24 hours. Use a unique key per logical send (for example, an order or signup ID).
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// SendBatchEmailsJSONBodyBcc0 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyBcc0 = string

// SendBatchEmailsJSONBodyBcc1 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyBcc1 = []string

// SendBatchEmailsJSONBody_Bcc defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBody_Bcc struct {
	union json.RawMessage
}

// SendBatchEmailsJSONBodyCc0 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyCc0 = string

// SendBatchEmailsJSONBodyCc1 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyCc1 = []string

// SendBatchEmailsJSONBody_Cc defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBody_Cc struct {
	union json.RawMessage
}

// SendBatchEmailsJSONBodyReplyTo0 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyReplyTo0 = string

// SendBatchEmailsJSONBodyReplyTo1 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyReplyTo1 = []string

// SendBatchEmailsJSONBody_ReplyTo defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBody_ReplyTo struct {
	union json.RawMessage
}

// SendBatchEmailsJSONBodyTo0 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyTo0 = string

// SendBatchEmailsJSONBodyTo1 defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBodyTo1 = []string

// SendBatchEmailsJSONBody_To defines parameters for SendBatchEmails.
type SendBatchEmailsJSONBody_To struct {
	union json.RawMessage
}

// GetBouncesParams defines parameters for GetBounces.
type GetBouncesParams struct {
	Page  *float32 `form:"page,omitempty" json:"page,omitempty"`
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetComplaintsParams defines parameters for GetComplaints.
type GetComplaintsParams struct {
	Page  *float32 `form:"page,omitempty" json:"page,omitempty"`
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUnsubscribesParams defines parameters for GetUnsubscribes.
type GetUnsubscribesParams struct {
	Page  *float32 `form:"page,omitempty" json:"page,omitempty"`
	Limit *float32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateEmailJSONBody defines parameters for UpdateEmail.
type UpdateEmailJSONBody = map[string]interface{}

// GetSuppressionsParams defines parameters for GetSuppressions.
type GetSuppressionsParams struct {
	Page   *float32                     `form:"page,omitempty" json:"page,omitempty"`
	Limit  *float32                     `form:"limit,omitempty" json:"limit,omitempty"`
	Search *string                      `form:"search,omitempty" json:"search,omitempty"`
	Reason *GetSuppressionsParamsReason `form:"reason,omitempty" json:"reason,omitempty"`
}

// GetSuppressionsParamsReason defines parameters for GetSuppressions.
type GetSuppressionsParamsReason string

// AddSuppressionJSONBody defines parameters for AddSuppression.
type AddSuppressionJSONBody struct {
	Email  openapi_types.Email          `json:"email"`
	Reason AddSuppressionJSONBodyReason `json:"reason"`
	Source *string                      `json:"source,omitempty"`
}

// AddSuppressionJSONBodyReason defines parameters for AddSuppression.
type AddSuppressionJSONBodyReason string

// CreateTemplateJSONBody defines parameters for CreateTemplate.
type CreateTemplateJSONBody struct {
	Content *string `json:"content,omitempty"`
	Html    *string `json:"html,omitempty"`
	Name    string  `json:"name"`
	Subject string  `json:"subject"`
}

// UpdateTemplateJSONBody defines parameters for UpdateTemplate.
type UpdateTemplateJSONBody struct {
	Content *string `json:"content,omitempty"`
	Html    *string `json:"html,omitempty"`
	Name    *string `json:"name,omitempty"`
	Subject *string `json:"subject,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody CreateApiKeyJSONBody

// CreateCampaignJSONRequestBody defines body for CreateCampaign for application/json ContentType.
type CreateCampaignJSONRequestBody CreateCampaignJSONBody

// ScheduleCampaignJSONRequestBody defines body for ScheduleCampaign for application/json ContentType.
type ScheduleCampaignJSONRequestBody ScheduleCampaignJSONBody

// CreateContactBookJSONRequestBody defines body for CreateContactBook for application/json ContentType.
type CreateContactBookJSONRequestBody CreateContactBookJSONBody

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody CreateContactJSONBody

// UpdateContactJSONRequestBody defines body for UpdateContact for application/json ContentType.
type UpdateContactJSONRequestBody UpdateContactJSONBody

// UpsertContactJSONRequestBody defines body for UpsertContact for application/json ContentType.
type UpsertContactJSONRequestBody = UpsertContactJSONBody

// UpdateContactBookJSONRequestBody defines body for UpdateContactBook for application/json ContentType.
type UpdateContactBookJSONRequestBody UpdateContactBookJSONBody

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody CreateDomainJSONBody

// SendEmailJSONRequestBody defines body for SendEmail for application/json ContentType.
type SendEmailJSONRequestBody SendEmailJSONBody

// SendBatchEmailsJSONRequestBody defines body for SendBatchEmails for application/json ContentType.
type SendBatchEmailsJSONRequestBody = SendBatchEmailsJSONBody

// UpdateEmailJSONRequestBody defines body for UpdateEmail for application/json ContentType.
type UpdateEmailJSONRequestBody = UpdateEmailJSONBody

// AddSuppressionJSONRequestBody defines body for AddSuppression for application/json ContentType.
type AddSuppressionJSONRequestBody AddSuppressionJSONBody

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody CreateTemplateJSONBody

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody UpdateTemplateJSONBody
